In [1]:
import os
import numpy as np

In [2]:
write_dir = '/n/netscratch/dvorkin_lab/Lab/kboone/cmb_conv/cls/'

try:
    os.mkdir(write_dir)
except Exception:
    pass

conv_dir = '/n/netscratch/dvorkin_lab/Lab/gvalogiannis/maps_cmbl_georgios/maps_cmbl_georgios/'

In [6]:
all_files = np.array(os.listdir(conv_dir))
# all_files = all_files[~np.isin(all_files, os.listdir(write_dir))]

fid_inds = [i for i, s in enumerate(all_files) if s.startswith('f')]
Om_inds = [i for i, s in enumerate(all_files) if s.startswith('O')]
s8_inds = [i for i, s in enumerate(all_files) if s.startswith('s')]

fid_files = all_files[fid_inds]
Om_files = all_files[Om_inds]
s8_files = all_files[s8_inds]

Om_crop_inds = [i for i, s in enumerate(Om_files) if (('flipped' not in s) & ('copy' not in s))]
Om_files = Om_files[Om_crop_inds]

In [9]:
np.load(conv_dir+Om_files[0], allow_pickle=True)[0]['full_sky_noiseless']

array([ 0.03288918, -0.0551739 , -0.03930486, ..., -0.00094235,
       -0.06609807,  0.00143892])

In [10]:
np.append([1, 2, 3], [])

array([1., 2., 3.])

In [19]:
wst_dir = '/n/netscratch/dvorkin_lab/Lab/kboone/cmb_conv/wst_numS50_L4/'

In [20]:
wst_files = os.listdir(wst_dir)

In [21]:
data = np.load(wst_dir + wst_files[0], allow_pickle=True).item()

In [23]:
data['ACT']

array([7.07857298, 7.26279448, 7.41746551, ..., 0.06546942, 0.06727631,
       0.06542138])